# Site settings
title: gabe.edwards.name
#email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabe.edwards.name"
twitter_username: gabedwrds
#github_username:  jekyll

# Build settings
markdown: kramdown
